---
namespace: ansible
name: memsource
version: 0.0.2
readme: README.md

authors:
  - Yanis Guenane <yguenane+opensource@gmail.com>
  - Christian Adams <chadams@redhat.com>
  - Aditya Mulik <aditya.mulik@gmail.com>

description: An Ansible collection to interact with Memsource

license:
  - Apache-2.0

tags:
  - memsource
  - translation
  - localization

dependencies: {}

repository: https://github.com/ansible/ansible-collection-memsource
documentation: https://github.com/ansible/ansible-collection-memsource
homepage: https://github.com/ansible/ansible.memsource
issues: https://github.com/ansible/ansible-collection-memsource/issues
