---
namespace: ansible

name: memsource

version: 0.0.1

readme: README.md

authors:
  - Ansible

description: An Ansible collection to interact with Memsource

license:
  - Apache-2.0

tags:
  - memsource
  - translation
  - localization

repository: https://github.com/ansible/ansible-collection-memsource

documentation: https://github.com/ansible/ansible-collection-memsource

homepage: https://github.com/ansible/ansible-collection-memsource

issues: https://github.com/ansible/ansible-collection-memsource/issues

build_ignore:
- 'docs'
- '.ci'
- 'tests'
- '.gitignore'
- '.github'
- '.git'
- '.pytest_cache'
- 'CONTRIBUTING.md'
- 'Makefile'