---
# Global declaration for github credentials
email: ""
github_username: ""
github_token: ""

# Global declaration for target languages
translation_supported_langs:
  - es
  - fr
  - nl
  - zh_cn
  - ja
  - ko

# Global declration for preTranslate (used cached strings for translation)
preTranslate: true

# Vars declaration for translations
upstream_repo_url: ""
repo_branch: ""
project_name: ""
project_template: 
downstream_repo_url: ""
project_uid: ""